# Nebulix Spatial - spf theme harmonieux

code_syntax_highlight = "base16-dark-nebulix"

# ========= Borders =========
file_panel_border      = "#304774"   # Bleu spatial
sidebar_border        = "#304774"
footer_border         = "#304774"

# ========= Borders Active =========
file_panel_border_active  = "#ffbe76"   # Orange pastel, accent doux
sidebar_border_active     = "#9d7dc1"   # Violet doux
footer_border_active      = "#9d5c5c"   # Bordeaux doux, touche subtile (accent)

# ========= Background (bg) =========
full_screen_bg        = "#181825"   # Fond spatial
file_panel_bg         = "#21233b"
sidebar_bg            = "#21233b"
footer_bg             = "#21233b"
modal_bg              = "#304774"

# ========= Foreground (fg) =========
full_screen_fg        = "#efe6d0"   # Crème, très doux
file_panel_fg         = "#efe6d0"
sidebar_fg            = "#efe6d0"
footer_fg             = "#efe6d0"
modal_fg              = "#efe6d0"

# ========= Special Color =========
cursor      = "#ffbe76"   # Orange pastel
correct     = "#4f81c7"   # Cyan spatial (succès)
error       = "#ecb6c5"   # Rose pâle (alerte douce)
hint        = "#9d7dc1"   # Violet doux
cancel      = "#304774"   # Bleu spatial

# Gradient color (pour certains accents)
gradient_color = ["#304774", "#ffbe76"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#efe6d0"    # Crème
file_panel_top_path           = "#9d7dc1"    # Violet doux
file_panel_item_selected_fg   = "#181825"    # Texte foncé sur sélection orange
file_panel_item_selected_bg   = "#ffbe76"    # Orange pastel sélection

# ========= Sidebar Special Items =========
sidebar_title            = "#ffbe76"    # Orange pastel
sidebar_item_selected_fg = "#181825"    # Texte foncé sur fond orange
sidebar_item_selected_bg = "#ffbe76"    # Fond orange pastel
sidebar_divider          = "#9d5c5c"    # Bordeaux doux, subtile

# ========= Modal Special Items =========
modal_cancel_fg   = "#efe6d0"
modal_cancel_bg   = "#ecb6c5"     # Rose pastel (calme)

modal_confirm_fg  = "#181825"
modal_confirm_bg  = "#ffbe76"     # Orange pastel

# ========= Help Menu =========
help_menu_hotkey  = "#ffbe76"
help_menu_title   = "#9d7dc1"

